teleop:
  hz: 8.0

  velocity:
    categories:
      horizontal: [1, 2, 3, 5, 10]
      vertical: [0.25, 0.5, 1, 2, 5]
      default_start_index: 0      # e.g. horizontal vel: horizontal[default_start_index] => 1 m/s

    yaw_rate: 1.0   # rad/s

  commands:
    params:
      KILL_SWITCH:
        activation_time_s: 1.0
        latch: true
        command_id: 1
        kill_window_s: 2.0
      KILL_CONFIRM:
        activation_time_s: 0.0
        latch: true
        command_id: 2
      CONTROL_TOGGLE:
        activation_time_s: 0.2
        latch: true
        command_id: 3
      CONSOLE_TOGGLE:
        activation_time_s: 1.0
        latch: true
        command_id: 4
      ARM:
        activation_time_s: 1.0
        latch: true
        command_id: 5
      DISARM:
        activation_time_s: 2.0
        latch: true
        command_id: 6
      LAND:
        activation_time_s: 0.5
        latch: true
        command_id: 7
      RTL:
        activation_time_s: 1.0
        latch: true
        command_id: 8
      LOITER:
        activation_time_s: 1.0
        latch: true
        command_id: 9
      TAKEOFF:
        activation_time_s: 1.0
        latch: true
        command_id: 10
      SPEED_UP:
        activation_time_s: 0.0
        latch: true
        command_id: 11
      SPEED_DOWN:
        activation_time_s: 0.0
        latch: true
        command_id: 12
      VEL_YAW:
        activation_time_s: 0.0
        latch: false
        command_id: 100